/**
 * @fileoverview Demo task data for guest mode.
 */

import {
  Ease,
  Enjoyment,
  Priority,
  SubtaskSortMode,
  TaskStatus,
  type TaskWithSubtasks,
  Time,
} from '~/shared/schema'

export const createDemoTasks = (nextIdRef: {
  current: number
}): TaskWithSubtasks[] => {
  const now = new Date()

  const getNextId = () => {
    const id = nextIdRef.current--
    return id
  }

  const parentWithSubtasksId = getNextId()
  const researchSubtaskId = getNextId()
  const completedWithSubtaskId = getNextId()

  const demoTasks: TaskWithSubtasks[] = [
    {
      id: getNextId(),
      userId: 'local',
      name: 'In Progress Demo Task (hold to change)',
      description:
        'This task is currently being worked on. Hold to change status.',
      priority: Priority.HIGH,
      ease: Ease.MEDIUM,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.MEDIUM,
      parentId: null,
      status: TaskStatus.IN_PROGRESS,
      inProgressTime: 120_000,
      inProgressStartedAt: new Date(now.getTime() - 120_000),
      createdAt: new Date(now.getTime() - 300_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Pinned Demo Task (hold to change)',
      description: 'This task is pinned to the top. Hold to change status.',
      priority: Priority.MEDIUM,
      ease: Ease.EASY,
      enjoyment: Enjoyment.HIGH,
      time: Time.LOW,
      parentId: null,
      status: TaskStatus.PINNED,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 250_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'High priority demo task',
      description: 'Example description for a high priority task.',
      priority: Priority.HIGH,
      ease: Ease.MEDIUM,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.LOW,
      parentId: null,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 60_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Easy demo task',
      description: 'Example description for an easy task.',
      priority: Priority.MEDIUM,
      ease: Ease.EASY,
      enjoyment: Enjoyment.HIGH,
      time: Time.LOW,
      parentId: null,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 120_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Funnest demo task!',
      description: 'Example description. This task is very enjoyable!',
      priority: Priority.LOW,
      ease: Ease.EASY,
      enjoyment: Enjoyment.HIGHEST,
      time: Time.LOWEST,
      parentId: null,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 180_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: parentWithSubtasksId,
      userId: 'local',
      name: 'Demo task with subtasks',
      description:
        'This task has nested subtasks to show how you can break down complex work.',
      priority: Priority.MEDIUM,
      ease: Ease.MEDIUM,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.HIGH,
      parentId: null,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 240_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: researchSubtaskId,
      userId: 'local',
      name: 'Research options',
      description: 'Look into different approaches',
      priority: Priority.MEDIUM,
      ease: Ease.EASY,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.LOW,
      parentId: parentWithSubtasksId,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 50_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Compare pricing tiers',
      description: 'A sub-subtask showing 3 levels of nesting',
      priority: Priority.LOW,
      ease: Ease.EASIEST,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.LOWEST,
      parentId: researchSubtaskId,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 45_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Draft initial plan',
      description: 'Write up the first draft',
      priority: Priority.MEDIUM,
      ease: Ease.MEDIUM,
      enjoyment: Enjoyment.HIGH,
      time: Time.MEDIUM,
      parentId: parentWithSubtasksId,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 40_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Review and finalize',
      description: 'Get feedback and make final edits',
      priority: Priority.LOW,
      ease: Ease.EASY,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.LOWEST,
      parentId: parentWithSubtasksId,
      status: TaskStatus.OPEN,
      inProgressTime: 0,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 30_000),
      completedAt: null,
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Completed subtask',
      description:
        'This subtask has been completed and stays under its parent.',
      priority: Priority.MEDIUM,
      ease: Ease.EASY,
      enjoyment: Enjoyment.HIGH,
      time: Time.LOWEST,
      parentId: parentWithSubtasksId,
      status: TaskStatus.COMPLETED,
      inProgressTime: 300_000,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 100_000),
      completedAt: new Date(now.getTime() - 20_000),
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Completed demo task',
      description: 'This task has already been finished.',
      priority: Priority.MEDIUM,
      ease: Ease.EASIEST,
      enjoyment: Enjoyment.HIGH,
      time: Time.LOWEST,
      parentId: null,
      status: TaskStatus.COMPLETED,
      inProgressTime: 9_000_000,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 300_000),
      completedAt: new Date(now.getTime() - 10_000),
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: completedWithSubtaskId,
      userId: 'local',
      name: 'Completed task with subtask',
      description: 'A completed root task that has a completed subtask.',
      priority: Priority.HIGH,
      ease: Ease.MEDIUM,
      enjoyment: Enjoyment.MEDIUM,
      time: Time.MEDIUM,
      parentId: null,
      status: TaskStatus.COMPLETED,
      inProgressTime: 1_800_000,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 400_000),
      completedAt: new Date(now.getTime() - 5000),
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
    {
      id: getNextId(),
      userId: 'local',
      name: 'Completed child task',
      description: 'A subtask that was completed along with its parent.',
      priority: Priority.MEDIUM,
      ease: Ease.EASY,
      enjoyment: Enjoyment.HIGH,
      time: Time.LOWEST,
      parentId: completedWithSubtaskId,
      status: TaskStatus.COMPLETED,
      inProgressTime: 600_000,
      inProgressStartedAt: null,
      createdAt: new Date(now.getTime() - 350_000),
      completedAt: new Date(now.getTime() - 8000),
      subtaskSortMode: SubtaskSortMode.INHERIT,
      subtaskOrder: [],
      subtasks: [],
    },
  ]

  return demoTasks
}
